### ISSUE TITLE
Make a branch off main for your work and create a pull request

### ISSUE THREAD

**Issue by abstractmachines** [devinenoise/cpp-learning#1]
This issue surfaces how to do [git branch workflow](https://www.youtube.com/watch?v=JTE2Fn_sCZs).

1. From your current branch which is called "main", `git push` all of your existing changes.
2. Make a new "feature" branch to represent your current work. `git checkout -b cpp-compiler-get-working`.
3. Look at the branches you have. `git branch`. You should see 2 branches, `main` and `cpp-compiler-get-working`.
4. Look at the history of `cpp-compiler-get-working` branch. Type `git log`. Note the last change. 
5. Compare that to changes on `main` branch. Type `git checkout main` and then, `git log`. Should look the same as the compiler branch.
6. Ok, get back on the `cpp-compiler-get-working` branch. 
7. Make a change. Commit it. Then push it up. `git push origin cpp-compiler-get-working`.
8. Now look at your Github main project page for this project. https://github.com/devinenoise/cpp-learning - and you should see "changes were recently pushed, wanna make a pull request"? Say Yes.
9. Add me as a reviewer to your PR (pull request). Hit save.

**Comment by abstractmachines** [comment]
@devinenoise This will also make it so I can review your work!

**Comment by devinenoise** [comment]
New branch created.
